# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mse1rNKDXPnbDZ_ACpoI-zignxpkuyCa
"""

def solution(progresses, speeds):

    answer = []
    times = 0
    temp = 0

    while len(progresses) > 0:
        if (progresses[0] + times * speeds[0]) >= 100:

            progresses.pop(0)
            speeds.pop(0)

            temp += 1

        else:
            if temp > 0:
                answer.append(temp)
                temp = 0
            else:
                times += 1

    answer.append(temp)

    return answer