# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mse1rNKDXPnbDZ_ACpoI-zignxpkuyCa
"""

def solution(bridge_length, weight, truck_weights):
    answer = 0
    bridge = [0] * bridge_length

    while len(bridge) > 0:

        answer += 1
        bridge.pop(0)

        if len(truck_weights) > 0:
            if sum(bridge) + truck_weights[0] <= weight:
                bridge.append(truck_weights.pop(0))
            else:
                bridge.append(0)

    return answer
