# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vuwgIlGmPOXD-w-MFZbcEkv_OYm8VUD4
"""

"""
def solution(prices):
    answer = []
    sec = 0

    while len(prices) > 1:
        for i in range(len(prices) - 1):
            if prices[0] <= prices[i+1]:
                sec += 1
            else:
                answer.append(sec + 1)
                prices.pop(0)
                sec = 0
                break

        answer.append(sec)
        prices.pop(0)
        sec = 0

    answer.append(0)

    return answer
"""
def solution(prices):
    answer = []

    for i in range(len(prices) - 1):
        sec = 0

        for j in range(i+1, len(prices)):
            sec += 1
            if prices[i] > prices[j]:
                break
        answer.append(sec)

    answer.append(0)

    return answer