# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mse1rNKDXPnbDZ_ACpoI-zignxpkuyCa
"""

def solution(s):
    count = 0
    for i in s:
        if count >= 0:
            if i == '(':
                count += 1
            else:
                count -= 1
        else:
            return False
    if count == 0:
        return True
    else:
        return False

