# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mse1rNKDXPnbDZ_ACpoI-zignxpkuyCa
"""

import collections

def solution(clothes):
    kind = []
    answer = 1

    for i in range(len(clothes)):
        kind.append(clothes[i][1])

    num = list(collections.Counter(kind).values())

    for i in range(len(num)):
            answer = answer * (num[i]+1)

    return answer - 1